name: flutter_lab
description: "Flutter Lab for training and experimentation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-221.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/