name: flutter_lab
description: "Flutter Lab for training and experimentation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-221.0.dev

dependencies:
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  mime: ^2.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/